{SHA}: {SHA}-updategit

{SHA}-updategit:
# If repo is already cloned, update it, else clone.
ifneq ("$(wildcard repositories/{SHA}/repo)","")
	git -C repositories/{SHA}/repo fetch
else
	git clone --bare --filter=tree:0 {REPO} repositories/{SHA}/repo
	# As a repo is added the tracked list needs to be rebuild.
	rm -f repositories.tracked.csv
endif

{SHA}-clean:
	rm -rf repositories/{SHA}

